name: MelonStats
version: '${project.version}'
main: org.melonmc.melonstats.MelonStats
api-version: 1.19
authors: [ Frxq15 ]
description: MelonMC Stats Plugin

commands:
  stats:
    usage: /stats <player>
    aliases: [s, playerstats]
  leaderboard:
    usage: /leaderboard
    aliases: [topstats, leaderboards, lb]
  topkills:
    usage: /topkills
    aliases: [highestkills]
  killstreaks:
    usage: /killstreaks
    aliases: [ks]
  resetstats:
    usage: /resetstats
    aliases: [rs]
